name: adding terraform with github_actions

on:
  push:
    branches:["master"]

  workflow_dispatch:

env:
    working_directory: ./pavani_module/example
    AWS_ACCESS_KEY_ID: ${{Secrete.AWS_ACCESS_KEY_ID}}
    AWS_SECRET_ACCESS_KEY: ${{Secrete.AWS_SECRET_ACCESS_KEY}}
    AWS_SESSION_TOKEN: ${{Secrete.AWS_SESSION_TOKEN}}
    AWS_DEFAULT_REGION: us-east-1

jobs:
  apply_the_terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses:  hashicorp/setup-terraform@v2

      - name: Terraform init
        id: init
        run: terraform init
        working_directory: ${{env.working_directory}}

      - name: Terraform validate
        id: validate
        run: terraform validate
        working_directory: ${{env.working_directory}}

      - name: Terraform plan
        id: plan
        run: terraform plan
        working_directory: ${{env.working_directory}}

      - name: Terraform plan status
        if: steps.plan.outcome == 'failure'
        run: echo "oops not done!"

      - name: Terraform apply
        id: apply
        if: steps.plan.outcome != 'failure'
        run: terraform apply -auto-approve
        working_directory: ${{env.working_directory}}

      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approve
        working_directory: ${{env.working_directory}}

