name: adding terraform github_actions

on:
  push:
    branches: ["main","master"]

  workflow_dispatch:

env:
    working_directory: ./pavani_module/example
    

jobs:
  apply_the_terraform:
    runs-on: ubuntu-latest

    env:
        AWS_ACCESS_KEY_ID: ${{secrete.aws_access_key_id}}
        AWS_SECRET_ACCESS_KEY: ${{secrete.aws_secret_access_key}}
        AWS_SESSION_TOKEN: ${{secrete.aws_session_token}}
        AWS_DEFAULT_REGION: us-east-1
        
    steps:
      - uses: actions/checkout@v3


      - name: Setup Terraform
        uses:  hashicorp/setup-terraform@v2

      - name: Terraform init
        id: init
        run: terraform init
        working_directory: ${{env.working_directory}}

      - name: Terraform validate
        id: validate
        run: terraform validate
        working_directory: ${{env.working_directory}}

      - name: Terraform plan
        id: plan
        run: terraform plan
        working_directory: ${{env.working_directory}}

      - name: Terraform plan status
        if: steps.plan.outcome == 'failure'
        run: echo "oops not done!"

      - name: Terraform apply
        id: apply
        if: steps.plan.outcome != 'failure'
        run: terraform apply -auto-approve
        working_directory: ${{env.working_directory}}

      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approve
        working_directory: ${{env.working_directory}}

